.TH midi2input 1

.SH NAME
midi2input \- Turns a midi device into a keyboard/mouse controller
.SH SYNOPSIS
.B midi2input
.SH DESCRIPTION
This program takes midi events from jackd and translates them to input events.Configuration is written in Lua.
.SH AUTHOR
Samuel Nicholas <nicholas.samuel@gmail.com>
